### ISSUE TITLE
Filter invalid sample rate values at input selection

### ISSUE THREAD

**Issue by LLDievelop** [pytchtracking/pytch#11]
At the moment, when configuring sound input, you can also choose a sample rate not compatible with the selected sound card, which leads to a crash. This should not be happening, instead pytch should determine the valid sample rates for the selected card and only offer these for selection.

**Comment by LLDievelop** [comment]
Found a [Stackoverflow issue](https://stackoverflow.com/questions/23553470) regarding this. It seems that this can't be done with PortAudio/PyAudio.

**Comment by HerrMuellerluedenscheid** [comment]
Nice! This was bugging me for quite some time. The article looks promising.
